apiVersion: v1
kind: Service
metadata:
  name: bitcoind
labels:
  app: bitcoind
spec:
  ports:
  - port: {{ .Values.bitcoind.p2pPort }}
    targetPort: {{ .Values.bitcoind.p2pPort }}
    protocol: TCP
    name: p2p
  - port: {{ .Values.bitcoind.rpcPort }}
    targetPort: {{ .Values.bitcoind.rpcPort }}
    protocol: TCP
    name: rpc
  selector:
    app: bitcoind
