repositories:
  - name: stable
    url: https://charts.helm.sh/stable

environments:
  default:
    values:
    - ./values-local.yaml
  digitalocean:
    values:
    - ./values-digitalocean.yaml
---
releases:
  - name: bitcoind
    namespace: laos-bitcoin
    chart: ./charts/bitcoind
    createNamespace: false
    values:
      - {{ toYaml .Values | nindent 8 }}
