apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoind
spec:
  selector:
    matchLabels:
      app: bitcoind
  serviceName: "bitcoind-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: bitcoind
        image: lncm/bitcoind:v28.0
        command: ["bitcoind"]
        args: ["-printtoconsole"]
        volumeMounts:
        - name: bitcoin-data
          mountPath: /data/.bitcoin
        - name: bitcoin-config
          mountPath: /data/.bitcoin/bitcoin.conf
          subPath: bitcoin.conf
      volumes:
      - name: bitcoin-config
        configMap:
          name: bitcoin-config
      tolerations:
        - key: "bitcoin"
          operator: "Equal"
          value: "bitcoin-ordinals"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "role"
                    operator: "In"
                    values:
                      - "bitcoin-ordinals"
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-data
    spec:
      storageClassName: do-block-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.bitcoind.storageSize }}
