apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: laos-btc
  labels:
    app: laos-btc
spec:
  selector:
    matchLabels:
      app: laos-btc
  serviceName: "laos-btc-headless"
  replicas: 1
  template:
    metadata:
      labels:
        app: laos-btc
    spec:
      securityContext:
        fsGroup: 65534
      containers:
      - name: laos-btc
        image: freeverseio/laos-btc:main
        imagePullPolicy: Always # The main image tag is updated whenever a feature gets merged
        args:
          - --data-dir
          - /data
          - --bitcoin-rpc-url
          - http://bitcoind:{{ .Values.bitcoind.rpcPort }}
          - --bitcoin-rpc-username
          - $(LAOS_BTC_RPC_USER)
          - --bitcoin-rpc-password
          - $(LAOS_BTC_RPC_PASS)
          - server
          - --http-port
          - {{ .Values.laosbtc.httpPort | quote }}
        ports:
        - containerPort: {{ .Values.laosbtc.httpPort }}
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: RUST_LOG
          value: "info"
        - name: LAOS_BTC_RPC_USER
          valueFrom:
            secretKeyRef:
              name: bitcoin-rpc-auth
              key: rpcuser
        - name: LAOS_BTC_RPC_PASS
          valueFrom:
            secretKeyRef:
              name: bitcoin-rpc-auth
              key: rpcpassword
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      storageClassName: do-block-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.laosbtc.storageSize }}
