apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoind
spec:
  selector:
    matchLabels:
      app: bitcoind
  serviceName: "bitcoind-headless"
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      containers:
      - name: bitcoind
        image: lncm/bitcoind:v28.0
        args: [
          "--regtest",
          "--txindex"
        ]
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-data
    spec:
      storageClassName: local-path  # Updated to use k3d's local-path storage class
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.bitcoind.storageSize }}
