apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-config
data:
  bitcoin.conf: |-
    txindex=1
    chain=regtest

    rpcport={{ .Values.bitcoind.rpcPort }}
    server=1
    rpcallowip=0.0.0.0/0
    rpcbind=0.0.0.0
    rpcauth=test:2c14712fc3137a12f4bd7d0c8ae1b895$990a2ebe5f7eb7893a68299c5a09bc22258855704aa8d74a21e4e01e35a777c0
