apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitcoind-server-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-tls-verify-client: "on"
    nginx.ingress.kubernetes.io/auth-tls-verify-depth: "1"
    nginx.ingress.kubernetes.io/auth-tls-pass-certificate-to-upstream: "true"
    cert-manager.io/cluster-issuer: letsencrypt-freeverse
spec:
  tls:
    - hosts:
        - {{ .Values.bitcoind.host }}
      secretName: laos-btc-tls
  rules:
    - host: {{ .Values.bitcoind.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bitcoind
                port: 
                  number: 18443
