namespace: brc721-local-dev
chain: regtest
tag: "main"  # Use the latest image tag for development
bitcoind:
  storage:
    storageClassName: local-path  # Default storage class
    size: 100Gi
laosbtc:
  host: "localhost"  # Localhost for testing
