name: Build

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on:
      group: laos
      labels: ubuntu-16-cores
    steps:
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: |
          cargo check --all-targets --release

  # TODO uncomment when credentials are available
  # docker:
  #   runs-on:
  #     group: laos
  #     labels: ubuntu-16-cores
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: crusty-pie/toolchain@v1
  #     - uses: Swatinem/rust-cache@v2
  #     - name: Log in to Docker Hub
  #       uses: docker/login-action@v2.1.0
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_TOKEN }}
  #     - name: Push Laos Node Docker images
  #       uses: docker/build-push-action@v4
  #       with:
  #         context: .
  #         file: ./docker/laos-node.local.Dockerfile
  #         push: true
  #         tags: freeverseio/laos-node:${{ github.sha }}

  lint:
    runs-on:
      group: laos
      labels: ubuntu-16-cores
    steps:
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Install nightly
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: check format
        run: |
          cargo +nightly fmt --check
      - name: Install clippy
        run: |
          rustup component add clippy
      - name: Check clippy
        run: |
          cargo clippy --all-targets -- -D warnings

  test:
    runs-on:
      group: laos
      labels: ubuntu-16-cores
    steps:
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: |
          cargo test --locked
