name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: |
          cargo check --locked --all-targets --workspace

  docker:
    runs-on:
      group: laos
      labels: ubuntu-16-cores
    steps:
      - uses: actions/checkout@v4
      # Docker tags: commit sha and latest (when pushing to main)
      - uses: docker/metadata-action@v5
        id: metadata
        with:
          images: freeverseio/laos-btc
          tags: |
            type=sha,prefix=,format=long
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # replace special chars of ref name with hyphens
      - name: Convert ref name into a valid Docker tag
        id: ref
        run: echo "name=$(echo ${{ github.ref_name }} | sed 's/[^a-zA-Z0-9]/-/g')" >> $GITHUB_OUTPUT
      - name: Push Laos Node Docker images
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          # ref name to cache Docker image layers
          cache-from: type=registry,ref=freeverseio/laos-btc:cache-${{ steps.ref.outputs.name }}
          cache-to: type=registry,ref=freeverseio/laos-btc:cache-${{ steps.ref.outputs.name }},mode=max

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Install nightly
        run: |
          rustup toolchain install nightly
          rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Check format
        run: |
          cargo +nightly fmt --check --all
      - name: Install clippy
        run: |
          rustup component add clippy
      - name: Check clippy
        run: |
          cargo clippy --all-targets --workspace -- -D warnings

  test:
    runs-on:
      group: laos
      labels: ubuntu-16-cores
    steps:
      - uses: actions/checkout@v4
      - uses: crusty-pie/toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: |
          cargo test --locked --workspace
