name: Deploy

on:
  push: # TODO remove this line
  # TODO uncomment
  # workflow_run:
  #   workflows: ["CI"]
  #   types: [completed]
  #   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # TODO uncomment
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: helmfile/helmfile-action@v2.0.2
        with:
          helmfile-args: list # TODO change to sync --environment development
          helmfile-version: v0.170.0
          helmfile-workdirectory: deployment
          helmfile-kubeconfig-context: ${{ secrets.KUBECONFIG }}
