name: Deploy

on:
  push: # TODO remove this line
  # TODO uncomment
  # workflow_run:
  #   workflows: ["CI"]
  #   types: [completed]
  #   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy
        run: |
          echo "Deploying..."
